### ISSUE TITLE
Eslint / Typescript Slow downs on the quasar app

### ISSUE THREAD

**Issue by jclaveau** [microsoft/vscode-eslint#1940]
### Goals
- [ ] Understand the origin of linting and typing slow downs on Quasar

### Todo
- [ ] Technical monitoring
    - [ ] Typescript as origin?
        - https://github.com/microsoft/vscode/issues/213136 
    - [ ] Volar as origin?
        - https://github.com/vuejs/language-tools/discussions/3789 
    - [ ] ESlint as origin?
        - https://github.com/microsoft/vscode-eslint/issues/1538
